{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: grafana
  {{- if .Values.grafana.vice_president }}
  annotations:
    vice-president: "true"
  {{- end}}

spec:
  tls:
     - secretName: "tls-{{.Values.grafana.endpoint.host.public | replace "." "-"}}"
       hosts: ["{{.Values.grafana.endpoint.host.public}}"]
  rules:
    - host: "{{.Values.grafana.endpoint.host.public}}"
      http:
        paths:
        - path: /
          backend:
            serviceName: grafana
            servicePort: {{.Values.grafana.endpoint.port.public}}
{{- end }}
