{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  {{- if .Values.ingress.vice_president }}
  annotations:
    vice-president: "true"
  {{- end}}
spec:
  {{- if or .Values.ingress.tls_crt .Values.ingress.vice_president}}
  tls:
     - secretName: {{ template "fullname" . }}
       hosts: [{{ .Values.ingress.host }}]
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end }}
