apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb
  namespace: backup-test
  labels:
    type: configuration
    component: mariadb

data:
  00_init.sh: |
    export TERM=dumb
    mysql -u root --password={{ .Values.root_password }} <<- EOSQL
      	CREATE DATABASE demo12 CHARACTER SET utf8 COLLATE utf8_general_ci;
      	CREATE DATABASE demo1234 CHARACTER SET utf8 COLLATE utf8_general_ci;
    EOSQL
