apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-etc
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: database

data:
  my.cnf: |
{{ include (print .Template.BasePath "/etc/_my.cnf.tpl") . | indent 4 }}
