{{- if and .Values.limes.certs .Values.limes.certs.tls_crt }}
{{ range $cluster_id, $config := .Values.limes.certs }}
apiVersion: v1
kind: Secret

metadata:
  name: limes-api-{{$cluster_id}}
  labels:
    app: limes-api

data:
  tls.crt: {{ b64enc $config.tls_crt }}
  tls.key: {{ b64enc $config.tls_key }}
---
{{end}}
{{- end }}
