apiVersion: v1
kind: ConfigMap

metadata:
  name: limes

data:
  policy.json: |
{{ .Files.Get "files/policy.json" | indent 4 }}
  limes.yaml: |
    database:
      location: "postgres://postgres:{{.Values.postgresql.postgresPassword}}@limes-postgresql.{{.Release.Namespace}}.svc/limes?sslmode=disable"

    api:
      listen: :80
      policy: /etc/limes/policy.json

    collector:
      metrics: :8080
      data_metrics: true
      auto_align_quotas: {{ .Values.limes.auto_align_quotas }}

    clusters:
{{ toYaml .Values.limes.clusters | indent 6 }}
  migrate.sh: |
    #!/bin/sh
    set -euo pipefail
    limes migrate /etc/limes/limes.yaml
    exec tail -f /dev/null
