kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: limes-migrate
  labels:
    app: limes-migrate
    release: "{{$.Release.Name}}"

spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: limes-migrate
  template:
    metadata:
      labels:
        name: limes-migrate
        app: limes-migrate
      annotations:
        checksum: {{ include "limes/templates/configmap.yaml" $ | sha256sum }}
    spec:
      volumes:
        - name: config
          configMap:
            name: limes
      containers:
        - name: collect
          image: {{include "limes_image" $}}
          imagePullPolicy: {{$.Values.limes.image_pull_policy}}
          command:
            - sh
          args:
            - /etc/limes/migrate.sh
          volumeMounts:
            - mountPath: /etc/limes
              name: config
