kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: swift-drive-autopilot
  namespace: swift
  labels:
    release: "{{.Release.Name}}"

spec:
  template:
    metadata:
      labels:
        component: swift-drive-autopilot
        from: daemonset
        release: "{{.Release.Name}}"
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"species","value":"swift-storage"}]'
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      nodeSelector:
        species: swift-storage
      volumes:
        - name: config
          configMap:
            name: swift-drive-autopilot
        - name: coreos
          hostPath:
            path: /
      containers:
        - name: boot
          image: {{.Values.global.imageRegistry}}/monsoon/swift-drive-autopilot:{{include "image_version" .}}
          securityContext:
            privileged: true
          args:
            - /etc/drive-autopilot/config.yaml
          # env:
          #   - name: 'DEBUG'
          #     value: '1'
          volumeMounts:
            - mountPath: /etc/drive-autopilot
              name: config
            - mountPath: /coreos
              name: coreos
          ports:
            - name: metrics
              containerPort: 9102
