dependencies:
  - name: memcached
    repository: file://../../common/memcached
    version: 0.0.1
  - name: postgresql
    repository: file://../../common/postgresql
    version: 0.3.0
  - name: pgmetrics
    repository: file://../../common/pgmetrics
    version: 0.1.0
