apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: blackbox-tests-api

data:
  os.password: {{ .Values.global.openstack.password | b64enc }}
  vc.password: {{ .Values.global.vcenter.password | b64enc }}