apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-db-init
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-init.sh: |
    #!/usr/bin/env bash
    export PGUSER=postgres
    psql <<- EOSQL
        CREATE DATABASE {{.Values.postgresql.postgresDatabase}};
        CREATE ROLE {{.Values.postgresql.dbUser}} WITH ENCRYPTED PASSWORD '{{.Values.postgresql.dbPassword}}' LOGIN;
        GRANT ALL PRIVILEGES ON DATABASE {{.Values.postgresql.postgresDatabase}} TO {{.Values.postgresql.dbUser}};
    EOSQL
