{{- if .Values.esx_node_info.enabled }}
{{- range $i, $config := .Values.vcenter_exporter.maia_vcenter_config -}}
{{ if ne $i 0 }}---{{ end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esx-node-info-{{$config.name}}
  namespace: maia
  labels:
    system: openstack
    service: metrics

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: esx-node-info-{{$config.name}}
      annotations:
        checksum/maia-templates-vcenter-exporter-configmap.yaml: {{ include "maia/templates/vcenter-operator-configmap.yaml" $ | sha256sum }}
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: maia-etc
          configMap:
            name: vcenter-exporter
      containers:
        - name: esx-node-info
          # remove the "string:" prefix which is used to prevent helm's --set option from reformatting plain numbers into floats in scientific notation
          image: {{$.Values.vcenter_exporter.docker_repo}}/esx-node-info:{{ $.Values.esx-node-info.image_version | replace "string:" "" }}
          imagePullPolicy: IfNotPresent
          command:
            - python
          args:
            - /esx-node-info.py
            - -c
            - /maia-etc/{{$config.name}}.yaml
          volumeMounts:
            - mountPath: /maia-etc
              name: maia-etc
          ports:
            - name: metrics
              containerPort: {{ $.Values.vcenter_exporter.listen_port }}
{{ end -}}
{{ end -}}
