{{- if .Values.maia.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: maia
  namespace: maia
  labels:
    system: openstack
    service: maia
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{.Values.maia.listen_port}}
spec:
  selector:
    component: maia
  ports:
    - name: api
      port: {{.Values.maia.listen_port}}
{{- end }}
