{{- if .Values.maia.enabled }}
{{- if .Values.maia.tls_crt }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: maia

data:
  tls.crt: {{ default "" .Values.maia.tls_crt | b64enc | quote }} 
  tls.key: {{ default "" .Values.maia.tls_key | b64enc | quote }}
{{- end }}
{{- end }}
