{{- if .Values.vcenter_exporter.enabled }}
{{ $vcenters := .Values.vcenter_exporter.maia_vcenter_config -}}
{{ $exporters := .Values.vcenter_exporter.exporter_types -}}
{{- range $i, $config := $vcenters -}}
{{- range $j, $exportertype := $exporters -}}
{{ if or $j $i }}---{{ end }}
kind: Service
apiVersion: v1
metadata:
  name: vcenter-exporter-{{$exportertype.name}}-{{$config.name}}
  namespace: maia
  labels:
    system: openstack
    service: metrics
    component: vcenter-exporter-{{$exportertype.name}}-{{$config.name}}
  annotations: {{ if eq $exportertype.collector "maia" }}
    maia.io/scrape: "true"
    maia.io/port: "{{$.Values.vcenter_exporter.listen_port}}" {{ else if eq $exportertype.collector "prometheus" }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{$.Values.vcenter_exporter.listen_port}}" {{ end }}
spec:
  selector:
    component: vcenter-exporter-{{$exportertype.name}}-{{$config.name}}
  ports:
    - name: metrics
      port: {{$.Values.vcenter_exporter.listen_port}}
{{ end -}}
{{ end -}}
{{ end -}}
