{{- if .Values.vcenter_exporter.enabled }}
{{ $vcenters := .Values.vcenter_exporter.maia_vcenter_config -}}
{{ $exporters := .Values.vcenter_exporter.exporter_types -}}
{{- range $i, $config := $vcenters -}}
{{- range $j, $exportertype := $exporters -}}
{{ if or $j $i }}---{{ end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vcenter-exporter-{{$exportertype.name}}-{{$config.name}}
  namespace: maia
  labels:
    system: openstack
    service: metrics

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: vcenter-exporter-{{$exportertype.name}}-{{$config.name}}
      annotations:
        checksum/maia-templates-vcenter-exporter-configmap.yaml: {{ include "maia/templates/vcenter-exporter-configmap.yaml" $ | sha256sum }}
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: maia-etc
          configMap:
            name: vcenter-exporter
      containers:
        - name: vcenter-exporter
          # remove the "string:" prefix which is used to prevent helm's --set option from reformatting plain numbers into floats in scientific notation
          image: {{$.Values.vcenter_exporter.docker_repo}}/vcenter-exporter:{{ $.Values.vcenter_exporter.image_version | replace "string:" "" }}
          imagePullPolicy: IfNotPresent
          command:
            - python
          args:
            - /vcenter-exporter/vcenter-exporter.py
            - -c
            - /maia-etc/{{$config.name}}-{{$exportertype.name}}.yaml
            - -t
            - {{$exportertype.name}} 
          volumeMounts:
            - mountPath: /maia-etc
              name: maia-etc
          ports:
            - name: metrics
              containerPort: {{ $.Values.vcenter_exporter.listen_port }}
{{ end -}}
{{ end -}}
{{ end -}}
