{{- if .Values.vcenter_exporter.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcenter-exporter
  labels:
    system: openstack
    service: metrics
    component: configuration
data:
{{- range $config := .Values.vcenter_exporter.maia_vcenter_config }}
  {{$config.name}}.yaml: |
    main:
      listen_port: '{{$.Values.vcenter_exporter.listen_port}}'
      host: '{{$config.vcenter_ip}}'
      user: '{{$config.username}}'
      password: '{{$config.password}}'
      port: 443
      ignore_ssl: True
      interval: 60
      log: 'INFO'
      shorter_names_regex: '{{$.Values.vcenter_exporter.shorter_names_regex}}'
      vm_metrics:
      - 'cpu.latency.average'
      - 'cpu.usage.average'
      - 'cpu.usagemhz.average'
      - 'cpu.wait.summation'
      - 'disk.usage.average'
      - 'mem.usage.average'
      - 'net.usage.average'
      - 'net.bytesRx.average'
      - 'net.bytesTx.average'
      - 'net.droppedRx.summation'
      - 'net.droppedTx.summation'
      - 'net.errorsRx.summation'
      - 'net.errorsTx.summation'
      - 'net.packetsRx.summation'
      - 'net.packetsTx.summation'
      - 'virtualDisk.read.average'
      - 'virtualDisk.write.average'
      - 'virtualDisk.readIOI.latest'
      - 'virtualDisk.writeIOI.latest'
      - 'virtualDisk.totalReadLatency.average'
      - 'virtualDisk.totalWriteLatency.average'
{{- end }}
{{- end }}
