{{- if .Values.vcenter_exporter.enabled }}
{{- range $i, $config := .Values.vcenter_exporter.maia_vcenter_config -}}
{{ if ne $i 0 }}---{{ end }}
kind: Service
apiVersion: v1
metadata:
  name: vcenter-exporter-{{$config.name}}
  namespace: maia
  labels:
    system: openstack
    service: metrics
    component: vcenter-exporter-{{$config.name}}
  annotations:
    maia.io/scrape: "true"
    prometheus.io/port: "{{$.Values.vcenter_exporter.listen_port}}"

spec:
  selector:
    component: vcenter-exporter-{{$config.name}}
  ports:
    - name: metrics
      port: {{$.Values.vcenter_exporter.listen_port}}
{{ end -}}
{{ end -}}
