apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: network-canary
spec:
  requires:
  # uncomment once keystone brings its own seed
  # - {{/* default .Release.Namespace .Values.global.keystoneNamespace */}}/keystone-seed
  - monsoon3/test-blackbox-seed

  domains:
  - name: cc3test
    projects:
    - name: test
      network_quota:
        subnetpool: 5
        subnet: 5
        network: 5
        rbac_policy: 10
        router: 3
      networks:
      - name: private_canary_test_cc3test
        tags:
        - blackbox-test
        subnets:
        - name: private_canary_test_cc3test_sub
          cidr: 10.180.0.0/16
          ip_version: 4
      routers:
      - name: private_canary_test_cc3test-TO-FloatingIP-External-monsoon3
        external_gateway_info:
          network: FloatingIP-external-monsoon3-01@monsoon3-net-infra@monsoon3
        interfaces:
        - subnet: private_canary_test_cc3test_sub

    - name: regression
      network_quota:
        subnetpool: 5
        subnet: 5
        network: 5
        rbac_policy: 10
        router: 3
      networks:
      - name: private_regression_cc3test
        tags:
        - regression-test
        subnets:
        - name: private_regression_cc3test_sub
          cidr: 10.180.0.0/16
          ip_version: 4
      routers:
      - name: private_regression_cc3test-TO-FloatingIP-External-monsoon3
        external_gateway_info:
          network: FloatingIP-external-monsoon3-01@monsoon3-net-infra@monsoon3
        interfaces:
        - subnet: private_regression_cc3test_sub

