apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: project-canary-seed
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

spec:
  requires:
  - monsoon3/domain-cc3test-seed

  domains:
  - name: cc3test
    description: 'Converged Cloud Testing'

    groups:
    - name: Administrators
      description: 'Test Administrators'
      users:
      - test_admin
      roles:
      - project: test
        role: admin
      - project: test
        role: volume_admin
      - project: test
        role: sharedfilesystem_admin
      - project: test
        role: network_admin
      - project: test
        role: compute_admin
      - project: test
        role: member

    projects:
    - name: test
      network_quota:
        subnetpool: 5
        subnet: 5
        network: 5
        rbac_policy: 10
        router: 3

