# Default values for manila.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  manila_api_port_admin: '8786'
  manila_api_port_internal: '8786'
  manila_api_port_public: '443'

debug: "True"

image_version_manila_api_m3: DEFINED-IN-REGION-CHART
image_version_manila_scheduler_m3: DEFINED-IN-REGION-CHART
image_version_manila_share_m3: DEFINED-IN-REGION-CHART

# Dictionary mapping availability-zones to shares
# shares:
#   nova1:
#     shares_netapp:
#      - name: DEFINED-IN-REGION-CHART
#        vserver: DEFINED-IN-REGION-CHART
#        host: DEFINED-IN-REGION-CHART
#        username: DEFINED-IN-REGION-CHART
#        password: DEFINED-IN-REGION-CHART
#        root_volume_aggregate: DEFINED-IN-REGION-CHART
#        aggregate_search_pattern: DEFINED-IN-REGION-CHART
#        port_search_pattern: DEFINED-IN-REGION-CHART
#        physical_network: DEFINED-IN-REGION-CHART
#        mtu: DEFINED-IN-REGION-CHART

shares: {}

db_name: manila
db_user: manila
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn: DEFINE-IN-REGION-CHART

postgres:
  name: manila

logging:
    formatters:
        context:
            class: oslo_log.formatters.ContextFormatter
        default:
            format: "%(message)s"
    handlers:
        stdout:
            class: StreamHandler
            args: "(sys.stdout,)"
            formatter: context
        "null":
            class: logging.NullHandler
            formatter: default
            args: "()"
        sentry:
            class: "raven.handlers.logging.SentryHandler"
            level: ERROR
            args: "()"
    loggers:
        root:
            handlers: "null"
            level: WARNING
        manila:
            handlers: stdout, sentry
            level: DEBUG
        amqp:
            handlers: stdout, sentry
            level: WARNING
        amqplib:
            handlers: stdout, sentry
            level: WARNING
        sqlalchemy:
            handlers: stdout, sentry
            level: WARNING
        boto:
            handlers: stdout, sentry
            level: WARNING
        suds:
            handlers: stdout, sentry
            level: INFO
        eventlet.wsgi.server:
            handlers: stdout, sentry
            level: INFO
