# Default values for manila.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  configuration_repository: REQUIRED
  configuration_revision: REQUIRED
  manila_api_port_admin: '8786'
  manila_api_port_internal: '8786'
  manila_api_port_public: '443'

debug: "True"

image_version_manila_api_m3: DEFINED-IN-REGION-CHART
image_version_manila_scheduler_m3: DEFINED-IN-REGION-CHART
image_version_manila_share_m3: DEFINED-IN-REGION-CHART

db_name: manila
db_user: manila
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn_key: DEFINE-IN-REGION-CHART

postgres:
  name: manila