# Default values for manila.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
debug: "True"

db_name: manila
db_user: manila
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn_key: DEFINE-IN-REGION-CHART

postgres:
  name: manila