apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: billing-seed
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  requires:
    #- monsoon3/keystone-seed
    - monsoon3/domain-cc3test-seed
    - swift/swift-seed
    - limes/limes-seed

  services:
  - name: sapcc-billing
    type: sapcc-billing
    description: 'SAP Converged Cloud Billing services'
    endpoints:
    - interface: public
      region: '{{.Values.global.region}}'
      url: 'https://billing.{{.Values.global.region}}.cloud.sap:64000'

  domains:
  - name: Default
    users:
    - name: billing
      description: 'Billing Service'
      password: {{ .Values.billingServicePassword | quote }}
      roles:
      - project: service
        role: service

  - name: ccadmin
    projects:
    - name: billing
      description: 'Billing Administration for Converged Cloud'
      roles:
      - user: billing@Default
        role: swiftoperator
      - user: billing@Default
        role: cloud_resource_viewer
      swift:
        enabled: true

  - name: cc3test
    projects:
    - name: billing_test
      description: 'project for used for testing the billing service'
    users:
    - name: billing_domain_adm
      description: 'user for changing cost-center assignment to domains'
      password: {{ .Values.cc3testBillingDomainAdmPassword | quote }}
      roles:
      - domain: cc3test
        role: admin
    - name: billing_domain_usr
      description: 'user for displaying accumulated costs on a domain'
      password: {{ .Values.cc3testBillingDomainUsrPassword | quote }}
      roles:
      - domain: cc3test
        role: member
    - name: billing_project_adm
      description: 'user for changing cost-center assignment to projects'
      password: {{ .Values.cc3testBillingProjectAdmPassword | quote }}
      roles:
      - project: billing_test
        role: admin
    - name: billing_project_usr
      description: 'user for displaying accumulated costs on a project'
      password: {{ .Values.cc3testBillingProjectUsrPassword | quote }}
      roles:
      - project: billing_test
        role: member
      - project: billing_test
        role: swiftoperator
    groups:
    - name: Administrators
      roles:
      - project: billing_test
        role: admin
