apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-content-repo

data:
  check-rhn: |
{{ .Files.Get "bin/check-rhn" | indent 4 }}
  sleep-until-midnight: |
{{ .Files.Get "bin/sleep-until-midnight" | indent 4 }}
