{{- range $repo, $config := .Values.repos }}
{{- if and ($.Capabilities.APIVersions.Has "batch/v1beta1") $config.schedule }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: content-repo-import-{{$repo}}
  namespace: content-repo
  labels:
    system: openstack
    component: content-repo
spec:
  schedule: {{$config.schedule}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    {{- tuple $repo $.Values | include "job_spec" | indent 4 }}

---
{{- else}}
apiVersion: batch/v1
kind: Job
metadata:
  name: content-repo-import-{{$repo}}
  namespace: content-repo
  labels:
    system: openstack
    component: content-repo
    {{- tuple $repo $.Values | include "job_spec" }}

---
{{end}}
{{end}}
