apiVersion: v1
kind: ConfigMap

metadata:
  name: statsd-content-repo

data:
  statsd-exporter.yaml: |
    mappings:
    - match: repo.*.last_run.*
      name: repo_sync_last_run
      labels:
        kind: $2
        repo: $1
    - match: repo.*.check.success
      name: repo_sync_check_success
      labels:
        rc: $2
        repo: $1
    - match: repo.*.check.httpcode
      name: repo_sync_check_httpcode
      labels:
        repo: $1
