apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-db-maintain
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    system: openstack
    type: configuration
    component: neutron

data:
  db-maintain.sh: |
    #!/usr/bin/env bash

    data_dir=/postgresql/data

    cp /postgresql-conf/postgresql.conf  $data_dir/postgresql.conf
    cp /postgresql-conf/pg-hba.conf  $data_dir/pg_hba.conf

    export PGUSER={{ default "postgres" .Values.postgresql.postgresUser }}
    psql <<- EOSQL
        ALTER ROLE {{ .Values.postgresql.dbUser }} WITH ENCRYPTED PASSWORD '{{ .Values.postgresql.dbPassword }}';
        ALTER ROLE {{ .Values.postgresql.postgresUser }} WITH ENCRYPTED PASSWORD '{{ .Values.postgresql.postgresPassword }}';
    EOSQL



