apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-etc-region
  labels:
    system: openstack
    type: configuration
    component: neutron


data:
  ml2-conf-aci.ini: |
{{ include (print .Template.BasePath "/etc/_ml2-conf-aci.ini.tpl") . | indent 4 }}



