apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-db-init
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    system: openstack
    type: configuration
    component: neutron
data:
  db-init.sh: |
    #!/usr/bin/env bash
    export PGUSER={{ default "postgres" .Values.postgresql.postgresUser }}
    psql <<- EOSQL
        CREATE DATABASE {{.Values.postgresql.postgresDatabase}};
        CREATE ROLE {{.Values.postgresql.dbUser}} WITH ENCRYPTED PASSWORD '{{.Values.postgresql.dbPassword}}' LOGIN;
        GRANT ALL PRIVILEGES ON DATABASE {{.Values.postgresql.postgresDatabase}} TO {{.Values.postgresql.dbUser}};
    EOSQL
