# Default values for domain-seeds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
# specify the k8s keystone namespace if it differs from the current chart
  keystoneNamespace: monsoon3

# AD/LDAP connection details
ldapUrl: ldaps://ldap.global.cloud.sap:636
ldapUser: CN=monsoon-service,CN=Users,DC=ad,DC=global,DC=cloud,DC=sap
ldapPassword: DEFINE_IN_REGION_VALUES
ldapSuffix: DC=ad,DC=global,DC=cloud,DC=sap

# CAM connection details
camApiUrl: https://spc40-emea.byd.sap.corp/sap/a1s/cam/v1/userprofiles
camUser: SPC_KEYS_CON
camPasword: DEFINE_IN_REGION_VALUES

# default domain - service user credentials
dbBackupServicePassword: DEFINE_IN_REGION_VALUES
concourseServicePassword: DEFINE_IN_REGION_VALUES
dockerRegistryServicePassword: DEFINE_IN_REGION_VALUES
imageBuildServicePassword: DEFINE_IN_REGION_VALUES
quayServicePassword: DEFINE_IN_REGION_VALUES
s4HanaServicePassword: DEFINE_IN_REGION_VALUES

# kubernikus domain - service user credentials
kubernikusAdminPassword: DEFINE_IN_REGION_VALUES

# cc3test domain - user credentials
cc3testAdminPassword: DEFINE_IN_REGION_VALUES
cc3testMemberPassword: DEFINE_IN_REGION_VALUES
cc3testUserPassword: DEFINE_IN_REGION_VALUES

# temporary until openstack services have their own helm-charts w. seeds
novaServicePassword: DEFINE_IN_REGION_VALUES
neutronServicePassword: DEFINE_IN_REGION_VALUES
