{{- if .Values.hermes.certs }}
{{ $config := .Values.hermes.certs }}
apiVersion: v1
kind: Secret

metadata:
  name: hermes-api
  labels:
    app: hermes-api

data:
  tls.crt: {{ b64enc $config.tls_crt }}
  tls.key: {{ b64enc $config.tls_key }}

---
{{- end }}