{{ if .Values.hermes.deploy_kibana }}
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: hermes
  labels:
    system: openstack
    service: audit
spec:
  selector:
    component: kibana
  ports:
    - port: {{.Values.hermes_kibana_port_public}}
{{ end }}
