global:
  image_namespace: DEFINED-IN-REGION-SECRETS
  image_repository: DEFINED-IN-REGION-SECRETS

pod:
  debug:
    db_purge: false

image_version_nova_db_purge: DEFINED-IN-REGION-SECRETS

nova:
  db_purge:
    enabled: False
    # purge instance entries older than n days
    older_than: 7
    # purge at max n entries in one run
    max_number: 50 
    # dry run mode, i.e. just pretend to purge the entries
    dry_run: true
    # run the purge every n minutes
    interval: 15
