apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-job-migration
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    system: openstack
    component: keystone
    type: job
spec:
  template:
    metadata:
      labels:
        name: keystone-job-migration
        system: openstack
        component: keystone
        type: job
      annotations:
        chart-version: {{.Chart.Version}}
        configmap-bin-hash: {{ include (print $.Template.BasePath "/configmap-bin.yaml") . | sha256sum }}
        configmap-etc-hash: {{ include (print $.Template.BasePath "/configmap-etc.yaml") . | sha256sum }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keystone-migration
          image: "{{ default "hub.global.cloud.sap" .Values.repository }}/{{ .Values.api.image }}:{{ .Values.api.imageTag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.api.imagePullPolicy | quote }}
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /scripts/db-sync"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: {{ .Release.Name }}-postgresql
          volumeMounts:
            - mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
              name: keystone-etc
            - mountPath: /etc/keystone/logging.conf
              subPath: logging.conf
              name: keystone-etc
            - mountPath: /scripts
              name: keystone-bin
      volumes:
        - name: keystone-etc
          configMap:
            name: keystone-etc
        - name: keystone-bin
          configMap:
            name: keystone-bin
