{{- define "fernet" -}}
{{- range $i, $secret := .Values.api.fernet.secrets -}}
{{  $i }}: {{ $secret | println }}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: keystone-fernet
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keystone
    type: config
  annotations:
    max_active_keys: {{ .Values.api.fernet.maxActiveKeys | default "3" | quote }}
data:
{{ include "fernet" . | indent 4 }}