{{- if .Values.sentry.enabled }}
{{- if not .Values.sentry.dsn }}
apiVersion: "sentry.sap.cc/v1"
kind: "SentryProject"
metadata:
  name: keystone-sentry

spec:
  name: keystone #slug of the project you want to use (or create
  team: openstack #slug of the team where the project should be created (if it doesn't exist)
{{- end }}
{{- end }}