apiVersion: v1
kind: Service
metadata:
  name: keystone
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keystone
    type: api
{{- if .Values.api.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{.Values.api.metrics.port}}"
{{- end }}
spec:
  selector:
    app: {{ template "fullname" . }}
  type: {{ default "ClusterIP" .Values.services.type }}
  ports:
    - name: public
      protocol: "TCP"
      port: {{ default "5000" .Values.services.public.port }}
      targetPort: 5000
    - name: admin
      protocol: "TCP"
      port: {{ default "35357" .Values.services.admin.port }}
      targetPort: 35357
{{- if .Values.services.externalip }}
  externalIPs: [
    {{ .Values.services.externalip | quote }}
    ]
{{- end }}
