kind: Service
apiVersion: v1

metadata:
  name: nginx-ingress-controller
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
spec:
  type: ClusterIP 
  selector:
    app: nginx-ingress-controller
  ports: 
    - name: http 
      port: 8080 
      targetPort: http
    - name: https 
      port: 443 
      targetPort: https
  externalIPs: 
    - {{.Values.external_service_ip}}
