apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: test-blackbox-seed
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  requires:
    - monsoon3/domain-cc3test-seed

  domains:
  - name: cc3test
    description: 'Converged Cloud Testing'

    projects:
    - name: regression
      description: 'CC-Test Regression Project'

    groups:
    - name: Administrators
      description: 'Test Administrators'
      users:
      - test_admin
      roles:
      - project: admin
        role: volume_admin
      - project: admin
        role: sharedfilesystem_admin
      - project: admin
        role: network_admin
      - project: admin
        role: compute_admin
      - project: admin
        role: member
      - project: test
        role: admin
      - project: test
        role: volume_admin
      - project: test
        role: sharedfilesystem_admin
      - project: test
        role: network_admin
      - project: test
        role: compute_admin
      - project: test
        role: member
      - project: regression
        role: admin
      - project: regression
        role: volume_admin
      - project: regression
        role: sharedfilesystem_admin
      - project: regression
        role: network_admin
      - project: regression
        role: compute_admin
      - project: regression
        role: member

