apiVersion: v1
kind: ConfigMap
metadata:
  name: designate-initdb
  labels:
    system: openstack
    type: configuration
    component: designate

data:
  init.sh: |
{{ include (print .Template.BasePath "/initdb/_init.sh.tpl") . | indent 4 }}
