# Deploy swift-account-caretaker
swift_account_caretaker:
  enable: true
  auth_url: DEFINED_IN_REGION_CHART
  password: DEFINED_IN_REGION_CHART
  # additional_clusters:
  #   cluster-X:
  #     os_auth_url: DEFINED_IN_REGION_CHART
  #     os_user_domain_name: DEFINED_IN_REGION_CHART
  #     os_username: DEFINED_IN_REGION_CHART
  #     os_password: DEFINED_IN_REGION_CHART
  #     os_project_domain_name: DEFINED_IN_REGION_CHART
  #     os_project_name: DEFINED_IN_REGION_CHART
  #     #scrape:
  #     #os_interface:
  #     #insecure:
