# Default values for backup-replication.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: false
repository: sapcc/backup-replication
image_version: v0.2.5

# in a future release it will be the cronjob time "5 */8 * * *" for every 8 hours
# currently its hardcoded 8 hours
# backup_replication_cronjob: "5 */8 * * *"

# this value are seconds 864000 are 10 days
backup_expire_after: 864000
from:
  os_auth_url: DEFINED-IN-REGION-SECRETS
  os_auth_version: DEFINED-IN-REGION-SECRETS
  os_username: DEFINED-IN-REGION-SECRETS
  os_user_domain: DEFINED-IN-REGION-SECRETS
  os_project_name: DEFINED-IN-REGION-SECRETS
  os_project_domain: DEFINED-IN-REGION-SECRETS
  os_region_name: DEFINED-IN-REGION-SECRETS
  os_password: DEFINED-IN-REGION-SECRETS
to:
  - os_auth_url: DEFINED-IN-REGION-SECRETS
    os_auth_version: DEFINED-IN-REGION-SECRETS
    os_username: DEFINED-IN-REGION-SECRETS
    os_user_domain: DEFINED-IN-REGION-SECRETS
    os_project_name: DEFINED-IN-REGION-SECRETS
    os_project_domain: DEFINED-IN-REGION-SECRETS
    os_region_name: DEFINED-IN-REGION-SECRETS
    os_password: DEFINED-IN-REGION-SECRETS
  - os_auth_url: DEFINED-IN-REGION-SECRETS
    os_auth_version: DEFINED-IN-REGION-SECRETS
    os_username: DEFINED-IN-REGION-SECRETS
    os_user_domain: DEFINED-IN-REGION-SECRETS
    os_project_name: DEFINED-IN-REGION-SECRETS
    os_project_domain: DEFINED-IN-REGION-SECRETS
    os_region_name: DEFINED-IN-REGION-SECRETS
    os_password: DEFINED-IN-REGION-SECRETS
