apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: prometheus-frontend
  labels:
    app: prometheus
    type: frontend

spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        type: frontend
    spec:
      terminationGracePeriodSeconds: 600
      containers:
        - name: prometheus 
          image: "{{.Values.global.prometheus.image}}:{{.Values.global.prometheus.tag}}"
          args:
            - -config.file=/etc/prometheus/prometheus.yaml
            - -storage.local.path=/prometheus
            - -storage.local.target-heap-size={{.Values.target_heap_size}}
            - -storage.local.retention={{.Values.retention}}
            - -web.console.libraries=/etc/prometheus/console_libraries
            - -web.console.templates=/etc/prometheus/consoles
            - -web.external-url=https://prometheus.{{.Values.global.region}}.{{.Values.global.domain}}
            - -storage.local.series-file-shrink-ratio={{ default 0.1 .Values.series_file_shrink_ratio }}
            - -log.level={{ default "info" .Values.log_level }}
          ports:
            - name: http 
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /prometheus
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name | quote }}
        - name: config
          configMap:
            name: prometheus-frontend
