kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.name | quote }}
  labels:
    app: prometheus
    type: global
spec:
  accessModes:
    - {{ .Values.persistence.access_mode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
