{{- if .Values.elk_kibana_tls_crt }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: kibana

data:
  tls.crt: {{ default "" .Values.elk_kibana_tls_crt | b64enc | quote }} 
  tls.key: {{ default "" .Values.elk_kibana_tls_key | b64enc | quote }}
{{- end }}