apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: kibana
  namespace: elk
    {{- if .Values.vice_president }}
  annotations:
    vice-president: "true"
  {{- end}}

spec:
  tls:
     - secretName: kibana
       hosts: [{{.Values.elk_kibana_endpoint_host_public}}]
  rules:
    - host: {{.Values.elk_kibana_endpoint_host_public}}
      http:
        paths:
        - path: /
          backend:
            serviceName: kibana
            servicePort: {{.Values.elk_kibana_port_public}}
