---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wall-e-etc
  labels:
    system: openstack
    service: logging
    component: configuration

data:
   curator.yml: |
{{ include "elk/templates/etc/_curator.yml.tpl" . | indent 4 }}
   delete_indices.yml: |
{{ include "elk/templates/etc/_delete_indices.yml.tpl" . | indent 4 }}
   jump.json: |
{{ include "elk/templates/etc/_jump.json.tpl" . | indent 4 }}

