image:
  repository: sapcc/vice-president
  tag: v201710111446
  pullPolicy: IfNotPresent
log_level: 1
metrics_port: 9091
president:
  resync_period_minutes: 4
  certificate_check_interval_minutes: 10
