global:
  tld: DEFINED_IN_VALUES_FILE
  region: DEFINED_IN_VALUES_FILE
  imageRegistry: DEFINED_IN_VALUES_FILE

# Version needs to be updated if bin-config map contents have changed
# That allows deplyoment specs in parent chart to be updated
version: 0.1.0

# OpenStack Swift release name
release: mitaka

# image version of Swift image
image_version: DEFINED_BY_PIPELINE

# Selecting swift-storage nodes
species: swift-storage
