{{- if .Values.swift_account_caretaker.enable }}
kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: swift-account-caretaker-collect
  labels:
    release: "{{.Release.Name}}"
    on-upgrade: recreate

spec:
  template:
    metadata:
      labels:
        component: swift-account-caretaker-collect
        from: daemonset
      annotations:
        {{- include "swift-common.daemonset_annotations" . | indent 8 }}
        checksum/caretaker.etc: {{ include "swift-utils/templates/caretaker-configmap.yaml" . | sha256sum }}
        version/swift-common.bin: {{ index .Values "swift-common" "version" }}
    spec:
      {{- include "swift-common.daemonset_tolerations" . | indent 6 }}
      # Run daemonset in Hostnetwork to get the real hostname
      hostNetwork: true
      nodeSelector:
        species: {{ .Values.species }}
      volumes:
        - name: caretaker-etc
          configMap:
            name: swift-account-caretaker
        - name: swift-common-bin
          configMap:
            name: {{ include "swift-common.bin_cm_name" . }}
        - name: swift-drives
          hostPath:
            path: /srv/node
        - name: swift-drive-state
          hostPath:
            path: /run/swift-storage/state
      containers:
        - name: caretaker
          image: {{ include "swift-common.image" . }}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /swift-common-bin/start
            - account-caretaker-collect
          # privileged access required for /swift-utils-bin/unmount-helper (TODO: use shared/slave mount namespace instead)
          securityContext:
            privileged: true
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /caretaker-etc
              name: caretaker-etc
            - mountPath: /swift-common-bin
              name: swift-common-bin
            - mountPath: /srv/node
              name: swift-drives
            - mountPath: /swift-drive-state
              name: swift-drive-state
{{- end }}
