apiVersion: "openstack.stable.sap.cc/v1"
kind: OpenstackSeed
metadata:
  name: kubernikus-seed

spec:
  requires:
  - {{.Values.global.keystoneNamespace}}/keystone-seed

  roles:
    - kubernikus_admin
    - kubernikus_member

  domains:
  - name: ccadmin

    projects:
    - name: kubernikus
      description: 'Regional Kubernikus Control-Plane'
      network_quota:
        router: 1
        network: 1
        subnet: 1
        port: 512
        security_group: 4 
        security_group_rule: 32
        floatingip: 5
        loadbalancer: 4
        healthmonitor: 4
        listener: 4
      networks:
      - name: default
        subnets:
          name: kubernikus
          cidr: 198.18.0.0/24
      routers:
      - name: default
        external_gateway_info:
          network: {{required "missing .external_gateway_info.network" .Values.external_gateway_info.network}}
        interfaces:
          - subnet: kubernikus

    groups:
    - name: CCADMIN_CLOUD_ADMINS
      roles:
      - project: kubernikus
        role: admin
      - project: kubernikus
        role: kubernikus_admin

