global:
  image_namespace: DEFINED-IN-REGION-SECRETS
  image_repository: DEFINED-IN-REGION-SECRETS

pod:
  debug:
    db_purge: false

image_version_cinder_db_purge: DEFINED-IN-REGION-SECRETS

cinder:
  db_purge:
    enabled: False
    # purge deleted cinder entities older than n days
    older_than: 7
    # run the purge every n minutes
    interval: 30
