kind: ConfigMap
apiVersion: v1
metadata:
  name: backup-replica-config
  namespace: backup
data:
  from.env: |-
    declare -x OS_AUTH_URL={{ .Values.from.os_auth_url | quote }}
    declare -x OS_AUTH_VERSION={{ .Values.from.os_auth_version | quote }}
    declare -x OS_USERNAME={{ .Values.from.os_username | quote }}
    declare -x OS_USER_DOMAIN_NAME={{ .Values.from.os_user_domain | quote }}
    declare -x OS_PROJECT_NAME={{ .Values.from.os_project_name | quote }}
    declare -x OS_PROJECT_DOMAIN_NAME={{ .Values.from.os_project_domain | quote }}
    declare -x OS_REGION_NAME={{ .Values.from.os_region_name | quote }}
    declare -x OS_PASSWORD={{ .Values.from.os_password | quote }}
{{- range $key, $val := .Values.to }}
  to{{- $key -}}.env: |-
    declare -x OS_AUTH_URL={{ $val.os_auth_url | quote }}
    declare -x OS_AUTH_VERSION={{ $val.os_auth_version | quote }}
    declare -x OS_USERNAME={{ $val.os_username | quote }}
    declare -x OS_USER_DOMAIN_NAME={{ $val.os_user_domain | quote }}
    declare -x OS_PROJECT_NAME={{ $val.os_project_name | quote }}
    declare -x OS_PROJECT_DOMAIN_NAME={{ $val.os_project_domain | quote }}
    declare -x OS_REGION_NAME={{ $val.os_region_name | quote }}
    declare -x OS_PASSWORD={{ $val.os_password | quote }}
{{- end }}
