apiVersion: v1
kind: Service
metadata:
  name: backup-replication
  namespace: backup
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9188"
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9188
      protocol: TCP
  selector:
    name: backup-replication
