apiVersion: v1
kind: Service
metadata:
  name: backup-replication
  namespace: backup
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
  selector:
    name: backup-replication
