apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nova-db-purge
  namespace: monsoon3
  labels:
    system: openstack
    service: nova-db-purge

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: nova-db-purge
      annotations:
        checksum/nova-db-purge-templates-nova-db-purge-bin-configmap.yaml: {{ include "nova-db-purge/templates/nova-db-purge-bin-configmap.yaml" . | sha256sum }}
        checksum/nova-db-purge-templates-bin-db-purge-start.tpl: {{ include "nova-db-purge/templates/bin/_nova-db-purge-start.tpl" . | sha256sum }}
        checksum/nova-db-purge-templates-bin-db-purge.tpl: {{ include "nova-db-purge/templates/bin/_nova-db-purge.tpl" . | sha256sum }}
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: nova-db-purge-bin
          configMap:
            name: nova-db-purge-bin
        - name: nova-etc
          configMap:
            name: nova-etc
      containers:
        - name: nova-db-purge
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-api:{{.Values.image_version_nova_db_purge}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "{{ if not .Values.pod.debug.db_purge }}/bin/bash /nova-db-purge-bin/nova-db-purge-start{{ else }}sleep inf{{ end }}"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPENDENCY_SERVICE
              value: "postgres-nova,nova-api"
          volumeMounts:
            - mountPath: /nova-db-purge-bin
              name: nova-db-purge-bin
            - mountPath: /nova-etc
              name: nova-etc
