apiVersion: v1
kind: Pod
metadata:
  name: backup-replication
  namespace: backup-test
  labels:
    app: replication
spec:
  containers:
  - image: hub.global.cloud.sap/monsoon/backup-replication:v0.2.0
    name: backup-replication
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
