# Default values for blackbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
project_id: DEFINED-IN-REGION-SECRETS
project_name: DEFINED-IN-REGION-SECRETS
project_domain: DEFINED-IN-REGION-SECRETS
image_id: DEFINED-IN-REGION-SECRETS
flavor_id: DEFINED-IN-REGION-SECRETS
availability_zones: DEFINED-IN-REGION-SECRETS
fixed_network_id: DEFINED-IN-REGION-SECRETS
floatip_network_id: DEFINED-IN-REGION-SECRETS
floatip_subnet_names: DEFINED-IN-REGION-SECRETS
floatip_subnet_ids: DEFINED-IN-REGION-SECRETS
automation_id: DEFINED-IN-REGION-SECRETS
automation_node_id: DEFINED-IN-REGION-SECRETS
timeout: 180
sleep:
  iterate: 300
  purge: 600
