kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: manila-api
  labels:
    system: openstack
    type: api
    component: manila
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: manila-api
  template:
    metadata:
      labels:
        name: manila-api
    spec:
      containers:
        - name: manila-api
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-manila-api:{{.Values.image_version_manila_api}}
          imagePullPolicy: IfNotPresent
          env:
            - name: COMMAND
              value: "manila-api --config-file /etc/manila/manila.conf"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "manila-migration"
            - name: DEPENDENCY_SERVICE
              value: "postgres-manila,rabbitmq"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.manila_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: manila-api
              containerPort: {{.Values.global.manila_api_port_internal}}
          volumeMounts:
            - mountPath: /var/lib/kolla/config_files
              name: manila-etc
      volumes:
        - name: manila-etc
          configMap:
            name: manila-etc
