apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-etc
  labels:
    system: openstack
    type: configuration
    component: manila

data:
  manila.conf: |
{{ tuple "etc/_manila.conf.tpl" . | include "template" | indent 4 }}
  policy.json: |
{{ tuple "etc/_manila-policy.json.tpl" . | include "template" | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
  config.json: |
    {"command": "kubernetes-entrypoint",
       "config_files":[
           {"source": "/var/lib/kolla/config_files/manila.conf", "dest": "/etc/manila/manila.conf", "owner": "manila", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/policy.json", "dest": "/etc/manila/policy.json", "owner": "manila", "perm": "0400"},
           {"source": "/var/lib/kolla/config_files/logging.conf", "dest": "/etc/manila/logging.conf", "owner": "manila", "perm": "0400"}
       ]
    }
