apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-etc
  labels:
    system: openstack
    type: configuration
    component: manila

data:
  manila.conf: |
{{ include "manila/templates/etc/_manila.conf.tpl" .| indent 4 }}
