apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-etc
  labels:
    system: openstack
    type: configuration
    component: manila

data:
  manila.conf: |
{{ include "etc/manila.conf" .| indent 4 }}
