kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: manila-scheduler
  labels:
    system: openstack
    type: backend
    component: manila
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: manila-scheduler
  template:
    metadata:
      labels:
        name: manila-scheduler
    spec:
      containers:
        - name: manila-scheduler
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-manila-scheduler-m3:{{.Values.image_version_manila_scheduler_m3}}
          imagePullPolicy: IfNotPresent
          command:
            - bash
          args:
            - /container.init/manila-scheduler-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /manila-etc
              name: manila-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: manila-etc
          configMap:
            name: manila-etc
        - name: container-init
          configMap:
            name: manila-bin
