kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: manila-scheduler
  namespace: {{.Release.Namespace}}
  labels:
    system: openstack
    type: backend
    component: manila
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: manila-scheduler
  template:
    metadata:
      labels:
        name: manila-scheduler
    spec:
      nodeSelector:
        zone: farm
      containers:
        - name: manila-scheduler
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-manila-scheduler-m3:{{.Values.global.image_version_manila_scheduler_m3}}
          imagePullPolicy: IfNotPresent
          command:
            - /openstack-kube/openstack-kube/scripts/_container_init
          args:
            - manila-scheduler-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /manila-etc
              name: manila-etc
            - mountPath: /openstack-kube
              name: openstack-kube
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: openstack-kube
          gitRepo:
            repository: {{.Values.global.configuration_repository}}
            revision: {{.Values.global.configuration_revision}}
        - name: manila-etc
          configMap:
            name: manila-etc
        - name: container-init
          configMap:
            name: manila-bin
