kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: sysctl
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: sysctl
    spec:
      {{- if ge .Capabilities.KubeVersion.Minor "7" }}
      tolerations:
      - key: "species"
        operator: "Equal"
        effect: "network"
      {{- end }}
      containers:
        - image: sapcc/sysctl:latest
          name: sysctl
          imagePullPolicy: Always
          securityContext:
            privileged: true
