# Default values for domain-seeds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
# specify the k8s keystone namespace if it differs from the current chart
  keystoneNamespace: monsoon3

external_gateway_info:
  network: FloatingIP-external-ccadmin@ccadmin-net-infra@ccadmin
