image_unbound: sapcc/unbound
image_unbound_exporter: sapcc/unbound_exporter
image_unbound_tag: latest 
image_unbound_exporter_tag: latest 
image_pullPolicy: IfNotPresent
port_unbound_exporter: 9107
externalIP: DEFINED-REGION-CHART
interface: 0.0.0.0
forward_addr1: DEFINED-REGION-CHART
forward_addr2: DEFINED-REGION-CHART
stub_addr1: DEFINED-REGION-CHART
stub_addr2: DEFINED-REGION-CHART
stub_addr3: DEFINED-REGION-CHART
stub_zone_name: DEFINED-REGION-CHART 
failure_domain_zone: b
