{{- range $az, $shares := .Values.shares -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-storage-availability-zone-{{$az}}
  labels:
    system: openstack
    type: configuration
    component: manila
data:
  storage-availability-zone.conf: |
    [DEFAULT]
    storage_availability_zone = {{$az}}
  config.json: |
    {"command": "kubernetes-entrypoint",
       "config_files":[
           {"source": "/var/lib/kolla/config_files/storage-availability-zone.conf", "dest": "/etc/manila/storage-availability-zone.conf", "owner": "manila", "perm": "0400"},
           {"source": "/manila-etc/manila.conf", "dest": "/etc/manila/manila.conf", "owner": "manila", "perm": "0400"},
           {"source": "/manila-etc/policy.json", "dest": "/etc/manila/policy.json", "owner": "manila", "perm": "0400"},
           {"source": "/manila-etc/logging.conf", "dest": "/etc/manila/logging.conf", "owner": "manila", "perm": "0400"}
       ]
    }
---
{{ tuple $ $az | include "scheduler" }}
---
{{- range $i, $share := $shares.shares_netapp -}}
{{ tuple $ $share | include "share_netapp" }}
---
{{ tuple $ $share | include "share_netapp_configmap" }}
{{ if lt $i (sub (len $shares.shares_netapp) 1) }}
---
{{end}}
{{- end -}}
{{- end -}}
