rule_files:
  - ./*.rules

scrape_configs:
- job_name: 'prometheus-global'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'prometheus-regions-federation'
  scheme: https
  scrape_interval: 30s
  scrape_timeout: 25s

  honor_labels: true
  metrics_path: '/federate'

  params:
    'match[]':
      - '{__name__=~"^ALERTS$"}'
      - '{__name__=~"^blackbox_.+"}'
      - '{__name__=~"^canary_.+"}'
      - '{__name__=~"^datapath_.+"}'
      - '{__name__=~"^kube_node_.+"}'
      - '{__name__=~"up"}'
      - '{__name__=~"^swift_cluster_storage_used_percent_.+"}'
      - '{__name__=~"^pg_database_size_bytes_gauge_average$"}'

  relabel_configs:
    - action: replace
      source_labels: [__address__]
      target_label: region
      regex: prometheus.(.+).cloud.sap
      replacement: $1

  static_configs:
    - targets:
      - 'prometheus.ap-au-1.cloud.sap'
      - 'prometheus.ap-cn-1.cloud.sap'
      - 'prometheus.ap-jp-1.cloud.sap'
      - 'prometheus.eu-de-1.cloud.sap'
      - 'prometheus.eu-nl-1.cloud.sap'
      - 'prometheus.na-ca-1.cloud.sap'
      - 'prometheus.na-us-1.cloud.sap'
      - 'prometheus.na-us-3.cloud.sap'
      - 'prometheus.staging.cloud.sap'

alerting:
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - "alertmanager.eu-de-1.cloud.sap"
      - "alertmanager.eu-nl-1.cloud.sap"
