image: prom/prometheus:v2.0.0
retention: 2160h0m0s # 90 days

persistence:
  name: data-prometheus-global-0
  access_mode: ReadWriteMany
  size: 300Gi

regions:
  - "staging"
  - "ap-au-1"
  - "ap-cn-1"
  - "ap-jp-1"
  - "eu-de-1"
  - "eu-nl-1"
  - "eu-ru-1"
  - "la-br-1"
  - "na-ca-1"
  - "na-us-1"
  - "na-us-3"
