kind: Secret
apiVersion: v1

metadata:
  name: mosquitto
data:
  mosquitto.conf: {{ include "mosquitto.conf" . | b64enc }}
  acl.conf: {{ include "acl.conf.tpl" .| b64enc}}
{{- if .Values.tls.enabled }}
  ca.crt: {{ default "" .Values.tls.caCertificate | b64enc }}
  server.key: {{ default "" .Values.tls.privateKey | b64enc }}
  server.crt: {{ default "" .Values.tls.certificate | b64enc }}
{{- end }}
