kind: Secret
apiVersion: v1

metadata:
  name: mosquitto
data:
  mosquitto.conf: {{ include "mosquitto.conf" . | b64enc }}
  acl.conf: |
    user O=arc-boker,OU=arc-api
    topic #
    pattern write registration/%o/%u/%c
    pattern write reply/+
    pattern read identity/%c
{{- if .Values.tls.enabled }}
  ca.crt: {{ default "" .Values.tls.caCertificate | b64enc }}
  server.key: {{ default "" .Values.tls.privateKey | b64enc }}
  server.crt: {{ default "" .Values.tls.certificate | b64enc }}
{{- end }}
