# Default values for billing-seeds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  region: cluster

# default domain billing service user password
billingServicePassword: secret123!

# cc3test domain - global user credentials (do not change in each region)
cc3testBillingDomainAdmPassword: Initial123!
cc3testBillingDomainUsrPassword: Initial123!
cc3testBillingProjectAdmPassword: Initial123!
cc3testBillingProjectUsrPassword: Initial123!
