{{- if .Values.swift_account_caretaker.enable }}
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: swift-account-caretaker-mergify
  namespace: swift
  labels:
    release: "{{.Release.Name}}"

spec:
  revisionHistoryLimit: 5
  # this job is not in any critical path, so 1 replica and Recreate is quite enough
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: swift-account-caretaker-mergify
  template:
    metadata:
      labels:
        component: swift-account-caretaker-mergify
      annotations:
        checksum/swift.bin: {{ include "swift/templates/bin-configmap.yaml" . | sha256sum }}
        checksum/caretaker.etc: {{ include "swift/templates/caretaker-configmap.yaml" . | sha256sum }}
    spec:
      volumes:
        - name: caretaker-etc
          configMap:
            name: swift-account-caretaker
        - name: swift-bin
          configMap:
            name: swift-bin
      containers:
        - name: caretaker
          image: {{.Values.global.docker_repo}}/ubuntu-source-swift-account-m3:{{.Values.image_version_swift_account}}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /swift-bin/swift-start
            - account-caretaker-mergify
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /caretaker-etc
              name: caretaker-etc
            - mountPath: /swift-bin
              name: swift-bin
{{- end }}
