{{- if .Values.swift_account_caretaker.enable }}
{{- if .Values.daemonsets }}
kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: swift-account-caretaker-collect
  namespace: swift
  labels:
    release: "{{.Release.Name}}"
    on-upgrade: recreate

spec:
  template:
    metadata:
      labels:
        component: swift-account-caretaker-collect
        from: daemonset
        restart: directly
      annotations:
        {{- include "swift_daemonset_annotations" . | indent 8 }}
        checksum/swift.bin: {{ include "swift/templates/bin-configmap.yaml" . | sha256sum }}
        checksum/caretaker.etc: {{ include "swift/templates/caretaker-configmap.yaml" . | sha256sum }}
    spec:
      # Run daemonset in Hostnetwork to get the real hostname
      hostNetwork: true
      nodeSelector:
        species: swift-storage
      volumes:
        - name: caretaker-etc
          configMap:
            name: swift-account-caretaker
        - name: swift-bin
          configMap:
            name: swift-bin
        - name: swift-drives
          hostPath:
            path: /srv/node
        - name: swift-drive-state
          hostPath:
            path: /run/swift-storage/state
      containers:
        - name: caretaker
          image: {{.Values.global.docker_repo}}/ubuntu-source-swift-account-m3:{{.Values.image_version_swift_account}}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /swift-bin/swift-start
            - account-caretaker-collect
          # privileged access required for /swift-bin/unmount-helper (TODO: use shared/slave mount namespace instead)
          securityContext:
            privileged: true
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /caretaker-etc
              name: caretaker-etc
            - mountPath: /swift-bin
              name: swift-bin
            - mountPath: /srv/node
              name: swift-drives
            - mountPath: /swift-drive-state
              name: swift-drive-state
{{- end }}
{{- end }}
