apiVersion: v1
kind: ConfigMap
metadata:
  name: swift-bin
  labels:
    system: openstack
    service: objectstore
    component: configuration

data:
{{ .Files.Get "bin/nginx-start" | indent 4 }}
  rsyncd-start: |
