apiVersion: v1
kind: ConfigMap
metadata:
  name: swift-bin
  labels:
    system: openstack
    service: objectstore
    component: configuration

data:
  common.sh: |
{{ .Files.Get "bin/common.sh" | indent 4 }}
  health-statsd-wrap: |
{{ .Files.Get "bin/health-statsd-wrap" | indent 4 }}
  nginx-start: |
{{ .Files.Get "bin/nginx-start" | indent 4 }}
  rsyncd-start: |
{{ .Files.Get "bin/rsyncd-start" | indent 4 }}
  swift-start: |
{{ .Files.Get "bin/swift-start" | indent 4 }}
  unmount-helper: |
{{ .Files.Get "bin/unmount-helper" | indent 4 }}
