apiVersion: v1
kind: ConfigMap

metadata:
  name: swift-account-caretaker
  labels:
    system: openstack
    service: objectstore
    component: configuration

data:
  config.yaml: |
    {{- $caretaker := .Values.swift_account_caretaker }}
    common:
      os_auth_url: {{ $caretaker.common.os_auth_url }}
      os_user_domain_name: {{ $caretaker.common.os_user_domain_name }}
      os_username: {{ $caretaker.common.os_username }}
      os_password: {{ $caretaker.common.os_password }}
      os_project_domain_name: {{ $caretaker.common.os_project_domain_name }}
      os_project_name: {{ $caretaker.common.os_project_name }}
    verify:
      {{- range $index, $config := $caretaker.verify }}
      - cluster_name: {{ $index }}
        os_auth_url: {{ $config.os_auth_url }}
        os_user_domain_name: {{ $config.os_user_domain_name }}
        os_username: {{ $config.os_username }}
        os_password: {{ $config.os_password }}
        os_project_domain_name: {{ $config.os_project_domain_name }}
        os_project_name: {{ $config.os_project_name }}
        scrape: {{ $config.scrape | default false }}
        {{- if $config.os_interface }}
        os_interface: {{ $config.os_interface }}
        {{- end }}
        insecure: {{ $config.insecure | default false }}
      {{- end }}
