kind: Service
apiVersion: v1

metadata:
  name: memcached
  namespace: swift
  labels:
    release: "{{.Release.Name}}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9150"

spec:
  type: NodePort
  selector:
    name: memcached
  ports:
    - name: memcache
      port: 11211
