kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: swift-object-expirer
  namespace: swift
  labels:
    release: "{{.Release.Name}}"

spec:
  revisionHistoryLimit: 5
  # this job is not in any critical path, so 1 replica and Recreate is quite enough
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: swift-object-expirer
  template:
    metadata:
      labels:
        component: swift-object-expirer
      annotations:
        {{- include "swift_conf_annotations" . | indent 8 }}
        {{- include "swift_ring_annotations" . | indent 8 }}
    spec:
      volumes:
        - name: swift-bin
          configMap:
            name: swift-bin
        - name: swift-etc
          configMap:
            name: swift-etc
        - name: swift-account-ring
          configMap:
            name: swift-account-ring
        - name: swift-container-ring
          configMap:
            name: swift-container-ring
        - name: swift-object-ring
          configMap:
            name: swift-object-ring
      containers:
        - name: expirer
          image: {{.Values.global.docker_repo}}/ubuntu-source-swift-proxy-server-m3:{{.Values.image_version_swift_proxy}}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /swift-bin/swift-start
            - object-expirer
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /swift-bin
              name: swift-bin
            - mountPath: /swift-etc
              name: swift-etc
            - mountPath: /swift-rings/account
              name: swift-account-ring
            - mountPath: /swift-rings/container
              name: swift-container-ring
            - mountPath: /swift-rings/object
              name: swift-object-ring
