{{- range $index, $cluster := .Values.clusters }}
kind: Service
apiVersion: v1
metadata:
  name: swift-proxy-{{$cluster.name}}
  namespace: swift
  labels:
    release: "{{$.Release.Name}}"
    os-cluster: {{$cluster.name}}
  annotations:
    {{- include "swift_prometheus_annotations" . | indent 4 }}
spec:
  selector:
    component: swift-proxy-{{$cluster.name}}
  ports:
    - name: api
      port: {{$cluster.proxy_public_port}}
  externalIPs:
    - {{$cluster.proxy_public_ip}}
---
{{end}}
