{{- range $index, $cluster := .Values.clusters }}
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: swift-proxy-{{$cluster.name}}
  namespace: swift
  labels:
    release: "{{$.Release.Name}}"
    os-cluster: {{$cluster.name}}
spec:
  revisionHistoryLimit: 5
  replicas: {{$cluster.replicas}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- if eq $cluster.replicas 1.0 }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
      maxSurge: 2
  selector:
    matchLabels:
      component: swift-proxy-{{$cluster.name}}
  template:
    metadata:
      labels:
        component: swift-proxy-{{$cluster.name}}
      annotations:
        checksum/swift-cluster.etc: {{ include "swift/templates/etc/cluster-configmap.yaml" $ | sha256sum }}
        {{- include "swift_conf_annotations" $ | indent 8 }}
        {{- include "swift_ring_annotations" $ | indent 8 }}
    spec:
      volumes:
        - name: tls-secret
          secret:
            secretName: tls-swift-{{$cluster.name}}
        - name: swift-bin
          configMap:
            name: swift-bin
        - name: swift-etc
          configMap:
            name: swift-etc
        - name: swift-etc-cluster
          configMap:
            name: swift-etc-{{$cluster.name}}
        - name: swift-account-ring
          configMap:
            name: swift-account-ring
        - name: swift-container-ring
          configMap:
            name: swift-container-ring
        - name: swift-object-ring
          configMap:
            name: swift-object-ring
      containers:
        - name: proxy
          image: {{$.Values.global.docker_repo}}/ubuntu-source-swift-proxy-server-m3:{{$.Values.image_version_swift_proxy}}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /swift-bin/swift-start
            - proxy-server
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /swift-bin
              name: swift-bin
            - mountPath: /swift-etc
              name: swift-etc
            - mountPath: /swift-etc-cluster
              name: swift-etc-cluster
            - mountPath: /swift-rings/account
              name: swift-account-ring
            - mountPath: /swift-rings/container
              name: swift-container-ring
            - mountPath: /swift-rings/object
              name: swift-object-ring
        - name: nginx
          image: nginx:{{$.Values.image_version_auxiliary_nginx}}
          command:
            - /bin/sh
          args:
            - /swift-bin/nginx-start
          volumeMounts:
            - mountPath: /swift-bin
              name: swift-bin
            - mountPath: /swift-etc
              name: swift-etc
            - mountPath: /swift-etc-cluster
              name: swift-etc-cluster
            - mountPath: /tls-secret
              name: tls-secret
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{$cluster.proxy_public_port}}
              scheme: HTTPS
              httpHeaders:
                - name: Host
                  value: {{tuple $cluster $.Values | include "swift_endpoint_host"}}
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
        - name: collector
          image: {{$.Values.global.docker_repo}}/ubuntu-source-swift-proxy-server-m3:{{$.Values.image_version_swift_proxy}}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /swift-bin/swift-start
            - health-statsd
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            - name: STATSD_PORT
              value: "9125"
            - name: LOG_LEVEL
              value: "info"
            - name: ADD_HOSTNAME_SUFFIX
              value: "true"
          volumeMounts:
            - mountPath: /swift-bin
              name: swift-bin
            - mountPath: /swift-etc
              name: swift-etc
            - mountPath: /swift-rings/account
              name: swift-account-ring
            - mountPath: /swift-rings/container
              name: swift-container-ring
            - mountPath: /swift-rings/object
              name: swift-object-ring
        {{- include "swift_statsd_exporter_container" $ | indent 8 }}

---
{{end}}
