{{- if .Values.daemonsets }}
kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: swift-replicators
  namespace: swift
  labels:
    release: "{{.Release.Name}}"
    on-upgrade: recreate

spec:
  template:
    metadata:
      labels:
        component: swift-replicators
        from: daemonset
        restart: directly
      annotations:
        {{- include "swift_daemonset_annotations" . | indent 8 }}
        {{- include "swift_conf_annotations" . | indent 8 }}
        {{- include "swift_ring_annotations" . | indent 8 }}
    spec:
      # replicators need to discover their own IP, and it needs to match the
      # node IP in the ring file (this extra permission is why the replicators
      # form a separate daemonset)
      hostNetwork: true
      nodeSelector:
        species: swift-storage
      volumes: {{ include "swift_daemonset_volumes" . | indent 8 }}
      containers:
        {{- tuple "account"   "account-replicator"   . | include "swift_standard_container" | indent 8 }}
        {{- tuple "container" "container-replicator" . | include "swift_standard_container" | indent 8 }}
        {{- tuple "object"    "object-replicator"    . | include "swift_standard_container" | indent 8 }}

{{- end }}
