{{- range $index, $cluster := .Values.clusters }}
{{- if $cluster.tls_crt }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: tls-swift-{{$cluster.name}}

data:
  tls.crt: {{ $cluster.tls_crt | b64enc }}
  tls.key: {{ $cluster.tls_key | b64enc }}
---
{{end}}
{{end}}
