{{- range $index, $cluster := .Values.clusters }}
{{- if $cluster.seed }}
# If more than one cluster has seed = true, that should fail with having
# multiple seeds with the same name - wrong configured
apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: swift-seed
  labels:
    app: {{ tuple $.Release $.Chart $.Values | include "fullname" }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    component: objectstore
    type: seed
spec:
  requires:
  #- monsoon3/keystone-seed                 # uncomment once keystone is deployed via its own helm-charts chart
  #- monsoon3/glance-seed                   # uncomment once glance is deployed via its own helm-charts chart
  #- monsoon3/ironic-seed                   # uncomment once ironic is deployed via its own helm-charts chart
  - monsoon3/domain-default-seed
  - monsoon3/domain-bn-seed
  - monsoon3/domain-bs-seed
  - monsoon3/domain-ccadmin-seed
  - monsoon3/domain-hcp03-seed
  - monsoon3/domain-hcm-seed
  - monsoon3/domain-hec-seed
  - monsoon3/domain-monsoon3-seed
  - monsoon3/domain-s4-seed
  - monsoon3/domain-cc3test-seed

  roles:
  - swiftoperator
  - swiftreseller

  services:
  - name: swift
    type: object-store
    description: Openstack Object Store
    endpoints:
    - interface: admin
      region: '{{ $.Values.global.region }}'
      url: 'https://{{ tuple $cluster $.Values | include "swift_endpoint_host" }}:{{ $cluster.proxy_public_port }}/v1'
    - interface: internal
      region: '{{ $.Values.global.region }}'
      url: 'https://{{ tuple $cluster $.Values | include "swift_endpoint_host" }}:{{ $cluster.proxy_public_port }}/v1/AUTH_%(tenant_id)s'
    - interface: public
      region: '{{ $.Values.global.region }}'
      url: 'https://{{ tuple $cluster $.Values | include "swift_endpoint_host" }}:{{ $cluster.proxy_public_port }}/v1/AUTH_%(tenant_id)s'

  domains:
  - name: Default
    users:
    - name: admin
      roles:
      - domain: Default
        role: swiftreseller
      - project: admin
        role: swiftreseller
    - name: swift
      description: 'Swift Service'
      password: '{{ $cluster.swift_service_password }}'
      roles:
      - project: service
        role: service
    - name: ironic
      roles:
      - project: service
        role: swiftoperator

    groups:
    - name: administrators
      roles:
      - domain: Default
        role: swiftreseller
      - project: admin
        role: swiftreseller

  - name: ccadmin
    projects:
    - name: cloud_admin
      roles:
      - user: admin@Default
        role: swiftreseller
      - group: CCADMIN_CLOUD_ADMINS
        role: swiftreseller
    - name: master # Swift account is enabled in swift-utils-seed
      roles:
      - group: CCADMIN_CLOUD_ADMINS
        role: swiftreseller
      - group: CCADMIN_DOMAIN_ADMINS
        role: swiftreseller
      - user: db_backup@Default
        role: swiftoperator
      - user: docker_registry@Default
        role: swiftoperator
      - user: glance@Default
        role: swiftoperator
      - user: image-build@Default
        role: swiftoperator
      - user: quay@Default
        role: swiftoperator
      - user: ironic@Default
        role: swiftoperator

  - name: monsoon3
    projects:
    - name: cc-demo
      roles:
      - group: MONSOON3_DOMAIN_ADMINS
        role: swiftoperator

  - name: cc3test
    users:
    - name: swift_dispersion
      description: 'Swift Dispersion'
      password: {{ $.Values.dispersion_password }}
      roles:
        # required for normal operation
      - project: swift_dispersion
        role: swiftoperator
        # required to enable Swift accounts (see below)
      - project: swift_dispersion
        role: swiftreseller
        # required to find project IDs from names (see below)
      - project: swift_dispersion
        role: service
    projects:
    - name: swift_test
      description: 'testing project for Swift and content-repo'
      swift:
        enabled: true
      # ^ Enabling the Swift account here does not work because when the
      # openstack-operator applies this seed, Swift is not available yet.
      # Instead, our CI has a post-deployment task which creates this Swift
      # account, using the swift_dispersion service user. This is why the
      # swift_dispersion user has the service and swiftreseller roles.
    - name: swift_dispersion
      description: 'dispersion of objects and containers'
      swift:
        enabled: true
      # ^ Same as above.
    groups:
    - name: Administrators
      roles:
      - project: swift_test
        role: admin
      - project: swift_test
        role: member
      - project: swift_dispersion
        role: admin
      - project: swift_dispersion
        role: member
{{- end }}
{{- end }}
