{{- if .Values.daemonsets }}
kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: swift-servers
  namespace: swift
  labels:
    release: "{{.Release.Name}}"
    on-upgrade: rolling-recreate

spec:
  template:
    metadata:
      labels:
        component: swift-servers
        from: daemonset
        restart: carefully
      annotations:
        {{- include "swift_daemonset_annotations" . | indent 8 }}
        {{- include "swift_conf_annotations" . | indent 8 }}
        {{- include "swift_ring_annotations" . | indent 8 }}
    spec:
      hostNetwork: true
      nodeSelector:
        species: swift-storage
      volumes: {{ include "swift_daemonset_volumes" . | indent 8 }}
      containers:
        {{- tuple "object"    "object-server"    . | include "swift_standard_container" | indent 8 }}
          ports:
            - name: swift-object
              hostPort: 6000
              containerPort: 6000
        {{- tuple "container" "container-server" . | include "swift_standard_container" | indent 8 }}
          ports:
            - name: swift-container
              hostPort: 6001
              containerPort: 6001
        {{- tuple "account"   "account-server"   . | include "swift_standard_container" | indent 8 }}
          ports:
            - name: swift-account
              hostPort: 6002
              containerPort: 6002
{{- end }}
